$ANSIBLE_VAULT;1.2;AES256;espanso
64386663373939373636663466626363306339353636373338643436643766373465333565343664
3730313238356639366439613866313362663631633030640a333831663532376637366262663836
66313132663536313962633462396638383065623638666663353432623731396335373762626666
3964356231346666320a363836376231626636326465396236393539326333656332353935616666
31353130393232343237373639333334633066383431383262333432383965353537633463326564
63643864353138613962373532646131663365376462623965626165353138313830303734333536
66316532363137633633393830363761396565373032343639656265323662383230396562326364
30346136346233363865636138393433626164343364393737623734666566623362613365363032
3033
