$ANSIBLE_VAULT;1.2;AES256;espanso
30346335626366653230363131663737353862626462393861376433363664333434636566333364
3033613136313663633538303261393433353835333033640a643161643665303666623161343932
33333561663132646139326330636239343239303163623436656636353933636635303636656637
3639373264343366300a303838366364346361653638353133323239336634633634666237653166
64326664643962636536303933336439633862616462626337356533373933366463363466323437
32306661646465333131626261366239383332366235336634376231313534303963616432653231
346530303063663132393937383330656337
