- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: Download rust installer
  when: cargo_exists.rc != 0
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: 0755
    force: true

- name: install rust/cargo
  when: cargo_exists.rc != 0
  shell: /tmp/sh.rustup.rs -y --no-modify-path

- name: Install tree-sitter-cli
  shell: cargo install --locked tree-sitter-cli
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
