$ANSIBLE_VAULT;1.2;AES256;espanso
66396237313562346562363765343832643762363465316635363262333339633466663032326431
3262633931643633636534613161646562663930323365300a373032353633313439646334306639
39326562663863643836393835353163386366623937386337656236306237316631386166613034
6161316466303565390a656133666638376265636339363730353561653634383532333762656261
61353039346330653536336630623563363461393731373531353938323232326534303637656436
35363036353738353332653062646666363130386532333363636263613037623537383465356262
62653134323233633063623366613962373931323530376665653438383332326532346334626137
65386239313636633237626231353733356532353165353964663433653533393262616430613539
34376165386139356138316139366233353638643663633836613966663466636664333130373733
63643332633766343832333931626432383063656265333265633237656632326237323163323730
35663739636663306330313937383335666263656137303931306230626563666636366232313334
65636163323638643638343835303161346165373330653736393761303566326466646239323337
62383733653966376461373930383330663664623031303362376430666130376632353931623738
35383237616132383235343263303036373338396262646439346238323331663937613264393036
31333634353430393266663832303666376430306135336633376232313134326365663763366436
65353665376130643239646161653436306237646535353365346666386661326133373132393635
36323566653534306434343930663035336566333639613564333761343031363964383730613566
36353834356366343662363638343932353831336334303032626438333465336666323835653462
626164373062613335366163323862383464
