$ANSIBLE_VAULT;1.2;AES256;espanso
32326436333165363766323130383964343534393764643130666230633738393738383231366239
6630326230383531623933653964376262383966366231320a656663356332623738326463326538
64393962366135316264346533363134613831333434613634316438336639303166613130326532
6334303361386238380a313662343761336637313837373438346233623835303164623566346135
65616635353262653931343936303165656166393165616163613162383461303933633766356336
30313961623737656461323461646332666362643664636237303139363535346265333631326432
66343139636332643033666263343565363130323137383332656436363639366364326538323330
35623065333938323366386564613962373363323339333538353537633632396637383331353036
66626434663064623138353963616238343332616333626336633534643864316133336565396361
63333735326239616532353030363032333230643762313431353633626364616334663331393664
34363364346239633262383439636163336261323032373236383162323737666236313934623337
61626333393439386364373932643433313931336533636432386164346532626664316639346639
66343465303462643964396331306437626665306534353563336363613136633933643733306563
32333663313531333462306535333330303635313634393935303432383362376637383735303366
64613766626435623966326639393038323963623664393366323235643362333239366331643030
32373036373161653734393536623966663034643431613236376132326139326434656437613835
33326630326134303435316464623063643331396433386639326537346230356333376538393661
32663633616131653862333535616235343162323466356462333462386665643634626162343433
373032316262393235653138616231306230
