$ANSIBLE_VAULT;1.2;AES256;espanso
32623063303630333439333363623633323939323532663530656331373838386330663138316361
3336656530633861366165316436666332343232653338370a333061643131343462643430613966
37623461373462613365616361316664626163316437316436383432366137336437333932333838
3534366534366232660a613536323365386135356361656139653262646438343334323663336530
34323565383165643437323734663436646661633033333463616666656537633331366434663363
66643631326363353739336438313333323033333864366534613034373961363136613965306439
30346265376564643436376162306239623963353338313863333634303837663234633938363834
37343262363931393736366634653934623665336535616364303962333937326236383132316633
65343439656164363830356430626636663861313663356638646361383139636438386262376333
39386132303139373930386362346464366263653037633435353466393963316634373036353364
64363631373034346530636132373862663434653934613864366166323966356130396463386264
39396437616636333836613930303063333034636166313230356666323431346330656432356232
31376537326332386663666161356565643835313235363834303730626563396364663335316163
61666230376133613231313637353834333533636363363962393436376339643030303731353435
37643334623034366233353464343066313162353466656432336363643564343136336135633636
39343433366436356338396431393830663962363765613862653165633030366531613532383265
35356536386135346664656363303031616239633339643231306566316237333766333135353362
35313462656461383730383663323632323732323830333633613034363436626162316666396465
65646566353835643330323431383863633436326537626561663136646664353432383062653335
64323336626465373163333036356664306230663034623662656338333438613038383136626434
66643936303730346562663437373536653238316130633738646435363836393736343634633365
64316337316365313762343838313631653566343339336533626439383936323062653037376333
35316539386534326138643731633964383237613363393636336662633866616636646438613265
63643164363463393332323738353366353336396163356535343963373435386663313932333139
37366135356163366630386461303266613763323066353036666362333062336662323666653938
36356636663164383733313663383530336639326532623230313864666237303630343632656434
613833346137313765373734366564316334
