$ANSIBLE_VAULT;1.2;AES256;espanso
30366435363030393762383861643837616336393262613563393436633562306139663666623637
3839366163336137343232633436653439653632623862330a306463663962643332656439636462
37636531366162366536326339336233333165323635363165393564333361326534373430363938
6365616166303831310a313432663431633265616332646364643465663063633631306361383037
64616164646438363431323064633965653437323163363434366139303632343038343563623331
66646563373864306236666364353937383766366364356639646663303835316266396433326662
39336432663830646537366632346338653563323865363431313464313735663461393439366438
34306232613239343732323339366664666266373933326639343065366163366438336239623637
30393331643639383262653437643762643230616235386432633761653662333036666166623137
61306364353464323930336161393734373832386436316236353931623637343934336636343564
34333564623465386230663436363465323166393034613335626334313565343931663262376635
37343334323739653337333831623338616239353932356633373365396365303761643836663163
35333638356235303963653532616433373464343832313039376631633732393266363232343962
34326339623238373735643531653263613437663138383134306639396333636636653034613663
33653866643161626338363331616332643266316138356362626638343634343137323861333739
39323232656437643562326566616532303635363462666462303439643335666336336535366539
32336637653135383438373839336435326332616538373932366363623664666462613062363635
38363530353939636439366430343532323530393936633332653834363133646130346636376665
66626131303862663162356634326439316239336461373366363333393332663530383062386364
35316164363930393934383633383765663530623535383930343330356561333434373236313232
37306330646135366434613338336230333535363963623433666335343266393064613038643430
63653232313630653334376666356237373834313233326261656337616630383365373933663936
31396232306535613231323335353730326537613330396239623934333239363733313763316365
63386462383638313265616663663462393434626663656563343835333534626339316434346365
38316531356536623139663161333530623162343731656233633235623730383837383464326639
32306431623365613965353637363331316636303361653564353731323761383362646336613535
343733356162373132303862313065643837
